# Generated by Django 5.0.7 on 2024-08-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refuelings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refueling_date', models.DateField(auto_now_add=True)),
                ('from_km', models.IntegerField()),
                ('to_km', models.IntegerField()),
                ('fuel_lt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fuel_cost', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
